pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls.Basic
import QtQuick.Layouts
import "../components"

Item {
    id: control

    required property AppUi ui
    required property var appController
    required property string fontFamily

    property string currentScriptId: ""
    property string savedScriptName: ""
    property string savedScriptCode: ""

    readonly property bool hasUnsavedChanges: nameField.text !== control.savedScriptName
                                               || codeField.text !== control.savedScriptCode

    Layout.fillWidth: true
    Layout.fillHeight: true

    function defaultCode() {
        return "-- parse(ctx) runs for each received MQTT message.\n"
                + "-- ctx.topic: received MQTT topic\n"
                + "-- ctx.payload: raw payload bytes as a Lua string\n"
                + "-- ctx.payloadBase64: raw payload encoded as Base64\n"
                + "-- ctx.payloadHex: raw payload encoded as uppercase hex bytes\n"
                + "-- ctx.decoded: payload decoded with the subscription format\n"
                + "-- ctx.decodeError: decode error text, or empty string when OK\n"
                + "-- ctx.format: subscription payload format name\n"
                + "-- ctx.timestamp: receive timestamp generated by the app\n"
                + "-- Return nil, boolean, number, string, or a table.\n"
                + "\n"
                + "function parse(ctx)\n"
                + "    return ctx.decoded\n"
                + "end\n"
    }

    function resetTestResult() {
        scriptTestPane.resetResult()
    }

    function loadScript(row) {
        control.currentScriptId = row.id || ""
        nameField.text = row.name || ""
        codeField.text = row.code || control.defaultCode()
        control.savedScriptName = nameField.text
        control.savedScriptCode = codeField.text
        control.resetTestResult()
    }

    function newScript() {
        control.currentScriptId = ""
        nameField.text = qsTr("New Lua Script")
        codeField.text = control.defaultCode()
        control.savedScriptName = nameField.text
        control.savedScriptCode = codeField.text
        control.resetTestResult()
        nameField.forceActiveFocus()
        nameField.selectAll()
    }

    function ensureSelection() {
        const rows = control.appController.scriptLibraryModel || []
        if (control.currentScriptId.length > 0) {
            for (let i = 0; i < rows.length; ++i) {
                if (rows[i].id === control.currentScriptId) {
                    return
                }
            }
        }

        if (rows.length > 0 && control.currentScriptId.length > 0) {
            control.loadScript(rows[0])
        } else if (rows.length > 0 && nameField.text.length === 0) {
            control.loadScript(rows[0])
        } else if (rows.length === 0 && nameField.text.length === 0) {
            control.newScript()
        }
    }

    function saveScript() {
        const savedId = control.appController.upsertScript(
                    control.currentScriptId,
                    nameField.text,
                    codeField.text)
        control.currentScriptId = savedId
        control.savedScriptName = nameField.text
        control.savedScriptCode = codeField.text
    }

    function deleteCurrentScript() {
        if (control.currentScriptId.length === 0) {
            control.newScript()
            return
        }

        if (control.appController.deleteScript(control.currentScriptId)) {
            const rows = control.appController.scriptLibraryModel || []
            if (rows.length > 0) {
                control.loadScript(rows[0])
            } else {
                control.newScript()
            }
        }
    }

    Component.onCompleted: control.ensureSelection()

    Connections {
        target: control.appController

        function onScriptLibraryChanged() {
            control.ensureSelection()
        }
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 12
        spacing: 8

        SplitView {
            Layout.fillWidth: true
            Layout.fillHeight: true
            orientation: Qt.Horizontal

            handle: Rectangle {
                implicitWidth: 10
                implicitHeight: 10
                color: SplitHandle.pressed || SplitHandle.hovered
                       ? control.ui.themePalette.selectedBorder
                       : "transparent"

                Rectangle {
                    anchors.centerIn: parent
                    width: 1
                    height: parent.height
                    color: SplitHandle.pressed || SplitHandle.hovered
                           ? control.ui.themePalette.selectedBorder
                           : control.ui.themePalette.separator
                }
            }

            ScriptListPane {
                ui: control.ui
                appController: control.appController
                currentScriptId: control.currentScriptId
                onNewScriptRequested: control.newScript()
                onScriptRequested: (row) => control.loadScript(row)
            }

            Item {
                SplitView.fillWidth: true
                SplitView.minimumWidth: 420

                ColumnLayout {
                    anchors.fill: parent
                    anchors.leftMargin: 12
                    anchors.rightMargin: 12
                    spacing: 10

                    AppTextField {
                        id: nameField
                        ui: control.ui
                        Layout.fillWidth: true
                        Layout.minimumWidth: 0
                        placeholderText: qsTr("Script name")
                    }

                    AppTextArea {
                        id: codeField
                        ui: control.ui
                        Layout.fillWidth: true
                        Layout.fillHeight: true
                        Layout.minimumWidth: 0
                        Layout.minimumHeight: 360
                        font.family: "Menlo"
                        clip: true
                        showLineNumbers: true
                        showFocusBorder: false
                        wrapMode: TextEdit.NoWrap
                        placeholderText: qsTr("function parse(ctx)")
                    }

                    RowLayout {
                        Layout.fillWidth: true
                        spacing: 8

                        Label {
                            text: control.hasUnsavedChanges
                                  ? qsTr("Unsaved changes")
                                  : (control.currentScriptId.length > 0
                                     ? qsTr("Saved script")
                                     : qsTr("Draft script"))
                            color: control.hasUnsavedChanges
                                   ? control.ui.themePalette.warningText
                                   : control.ui.textMuted
                            font.pixelSize: 12
                        }

                        Item {
                            Layout.fillWidth: true
                        }

                        AppButton {
                            ui: control.ui
                            text: qsTr("Delete")
                            enabled: control.currentScriptId.length > 0
                            minimumWidth: 78
                            onClicked: control.deleteCurrentScript()
                        }

                        AppButton {
                            ui: control.ui
                            text: qsTr("Save")
                            primary: true
                            enabled: control.hasUnsavedChanges
                            minimumWidth: 78
                            onClicked: control.saveScript()
                        }
                    }
                }
            }

            ScriptTestPane {
                id: scriptTestPane
                ui: control.ui
                appController: control.appController
                scriptCode: codeField.text
            }
        }
    }
}
