#include "scriptstore.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHash>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QRegularExpression>
#include <QSaveFile>
#include <QStandardPaths>
#include <QUuid>

namespace {
struct FileBackup {
    bool existed = false;
    QByteArray content;
};

QString scriptStorageDirPath()
{
    const QString configRoot = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    const QString basePath = configRoot.isEmpty()
        ? QDir::home().filePath(QStringLiteral(".config"))
        : configRoot;
    return QDir(basePath).filePath(QStringLiteral("mqtt_plus/scripts"));
}

QString scriptIndexPath()
{
    return QDir(scriptStorageDirPath()).filePath(QStringLiteral("index.json"));
}

bool ensureScriptStorageDir(QString &errorMessage)
{
    QDir dir;
    if (dir.mkpath(scriptStorageDirPath())) {
        return true;
    }
    errorMessage = QStringLiteral("Cannot create script storage directory: %1").arg(scriptStorageDirPath());
    return false;
}

QString readScriptFile(const QString &fileName)
{
    QFile file(ScriptStore::scriptFilePath(fileName));
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return {};
    }
    return QString::fromUtf8(file.readAll());
}

bool writeTextFile(const QString &path, const QByteArray &content, QString &errorMessage)
{
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        errorMessage = QStringLiteral("Cannot open %1 for writing: %2").arg(path, file.errorString());
        return false;
    }
    if (file.write(content) != content.size()) {
        errorMessage = QStringLiteral("Cannot write %1: %2").arg(path, file.errorString());
        return false;
    }
    if (!file.commit()) {
        errorMessage = QStringLiteral("Cannot commit %1: %2").arg(path, file.errorString());
        return false;
    }
    return true;
}

FileBackup backupFile(const QString &path)
{
    FileBackup backup;
    QFile file(path);
    backup.existed = file.exists();
    if (backup.existed && file.open(QIODevice::ReadOnly)) {
        backup.content = file.readAll();
    }
    return backup;
}

void restoreBackups(const QHash<QString, FileBackup> &backups)
{
    QString ignoredError;
    for (auto it = backups.constBegin(); it != backups.constEnd(); ++it) {
        if (it.value().existed) {
            writeTextFile(it.key(), it.value().content, ignoredError);
        } else {
            QFile::remove(it.key());
        }
    }
}
}

namespace ScriptStore {
QString defaultLuaScript()
{
    return QStringLiteral(
        "-- parse(ctx) runs for each received MQTT message.\n"
        "-- ctx.topic: received MQTT topic\n"
        "-- ctx.payload: raw payload bytes as a Lua string\n"
        "-- ctx.payloadBase64: raw payload encoded as Base64\n"
        "-- ctx.payloadHex: raw payload encoded as uppercase hex bytes\n"
        "-- ctx.decoded: payload decoded with the subscription format\n"
        "-- ctx.decodeError: decode error text, or empty string when OK\n"
        "-- ctx.format: subscription payload format name\n"
        "-- ctx.timestamp: receive timestamp generated by the app\n"
        "-- Return nil, boolean, number, string, or a table.\n"
        "\n"
        "function parse(ctx)\n"
        "    return ctx.decoded\n"
        "end\n");
}

QString scriptFilePath(const QString &fileName)
{
    return QDir(scriptStorageDirPath()).filePath(QFileInfo(fileName).fileName());
}

QString scriptFileNameForId(const QString &id)
{
    QString safeId = id.trimmed();
    safeId.replace(QRegularExpression(QStringLiteral("[^A-Za-z0-9_-]")), QStringLiteral("_"));
    if (safeId.isEmpty()) {
        safeId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    }
    return QStringLiteral("%1.lua").arg(safeId);
}

LoadResult loadScripts()
{
    LoadResult result;

    QFile indexFile(scriptIndexPath());
    if (indexFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QJsonParseError parseError;
        const QJsonDocument document = QJsonDocument::fromJson(indexFile.readAll(), &parseError);
        if (parseError.error != QJsonParseError::NoError || !document.isObject()) {
            result.indexWritable = false;
            return result;
        }

        const QJsonArray scripts = document.object().value(QStringLiteral("scripts")).toArray();
        result.scripts.reserve(scripts.size());
        for (const QJsonValue &value : scripts) {
            const QJsonObject object = value.toObject();
            AppController::ScriptEntry script;
            script.id = object.value(QStringLiteral("id")).toString();
            script.name = object.value(QStringLiteral("name")).toString();
            script.fileName = object.value(QStringLiteral("fileName")).toString(scriptFileNameForId(script.id));
            script.updatedAt = object.value(QStringLiteral("updatedAt")).toString();
            if (script.id.isEmpty() || script.name.trimmed().isEmpty()) {
                continue;
            }
            script.code = readScriptFile(script.fileName);
            if (script.code.trimmed().isEmpty()) {
                script.code = defaultLuaScript();
            }
            result.scripts.append(script);
        }
    }

    return result;
}

bool saveScripts(QVector<AppController::ScriptEntry> &scripts, bool indexWritable, QString &errorMessage)
{
    errorMessage.clear();
    if (!indexWritable) {
        errorMessage = QStringLiteral("Script index is not writable.");
        return false;
    }
    if (!ensureScriptStorageDir(errorMessage)) {
        return false;
    }

    QHash<QString, FileBackup> backups;
    for (const auto &script : scripts) {
        const QString fileName = script.fileName.isEmpty() ? scriptFileNameForId(script.id) : script.fileName;
        const QString path = scriptFilePath(fileName);
        if (!backups.contains(path)) {
            backups.insert(path, backupFile(path));
        }
    }

    QJsonArray scriptRows;
    for (auto &script : scripts) {
        if (script.fileName.isEmpty()) {
            script.fileName = scriptFileNameForId(script.id);
        }
        if (!writeTextFile(scriptFilePath(script.fileName), script.code.toUtf8(), errorMessage)) {
            restoreBackups(backups);
            return false;
        }

        QJsonObject object;
        object.insert(QStringLiteral("id"), script.id);
        object.insert(QStringLiteral("name"), script.name);
        object.insert(QStringLiteral("fileName"), script.fileName);
        object.insert(QStringLiteral("updatedAt"), script.updatedAt);
        scriptRows.append(object);
    }

    QJsonObject root;
    root.insert(QStringLiteral("version"), 1);
    root.insert(QStringLiteral("scripts"), scriptRows);
    if (!writeTextFile(scriptIndexPath(), QJsonDocument(root).toJson(QJsonDocument::Indented), errorMessage)) {
        restoreBackups(backups);
        return false;
    }
    return true;
}

void removeScriptFile(const QString &fileName)
{
    if (!fileName.isEmpty()) {
        QFile::remove(scriptFilePath(fileName));
    }
}
}
