#include "scriptstore.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QRegularExpression>
#include <QSaveFile>
#include <QStandardPaths>
#include <QUuid>

namespace {
QString scriptStorageDirPath()
{
    const QString configRoot = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    const QString basePath = configRoot.isEmpty()
        ? QDir::home().filePath(QStringLiteral(".config"))
        : configRoot;
    return QDir(basePath).filePath(QStringLiteral("mqtt_plus/scripts"));
}

QString scriptIndexPath()
{
    return QDir(scriptStorageDirPath()).filePath(QStringLiteral("index.json"));
}

bool ensureScriptStorageDir()
{
    QDir dir;
    return dir.mkpath(scriptStorageDirPath());
}

QString readScriptFile(const QString &fileName)
{
    QFile file(ScriptStore::scriptFilePath(fileName));
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return {};
    }
    return QString::fromUtf8(file.readAll());
}

bool writeTextFile(const QString &path, const QByteArray &content)
{
    QSaveFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }
    if (file.write(content) != content.size()) {
        return false;
    }
    return file.commit();
}
}

namespace ScriptStore {
QString defaultLuaScript()
{
    return QStringLiteral(
        "-- parse(ctx) runs for each received MQTT message.\n"
        "-- ctx.topic: received MQTT topic\n"
        "-- ctx.payload: raw payload bytes as a Lua string\n"
        "-- ctx.payloadBase64: raw payload encoded as Base64\n"
        "-- ctx.payloadHex: raw payload encoded as uppercase hex bytes\n"
        "-- ctx.decoded: payload decoded with the subscription format\n"
        "-- ctx.decodeError: decode error text, or empty string when OK\n"
        "-- ctx.format: subscription payload format name\n"
        "-- ctx.timestamp: receive timestamp generated by the app\n"
        "-- Return nil, boolean, number, string, or a table.\n"
        "\n"
        "function parse(ctx)\n"
        "    return ctx.decoded\n"
        "end\n");
}

QString scriptFilePath(const QString &fileName)
{
    return QDir(scriptStorageDirPath()).filePath(QFileInfo(fileName).fileName());
}

QString scriptFileNameForId(const QString &id)
{
    QString safeId = id.trimmed();
    safeId.replace(QRegularExpression(QStringLiteral("[^A-Za-z0-9_-]")), QStringLiteral("_"));
    if (safeId.isEmpty()) {
        safeId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    }
    return QStringLiteral("%1.lua").arg(safeId);
}

LoadResult loadScripts()
{
    LoadResult result;

    QFile indexFile(scriptIndexPath());
    if (indexFile.open(QIODevice::ReadOnly | QIODevice::Text)) {
        QJsonParseError parseError;
        const QJsonDocument document = QJsonDocument::fromJson(indexFile.readAll(), &parseError);
        if (parseError.error != QJsonParseError::NoError || !document.isObject()) {
            result.indexWritable = false;
            return result;
        }

        const QJsonArray scripts = document.object().value(QStringLiteral("scripts")).toArray();
        result.scripts.reserve(scripts.size());
        for (const QJsonValue &value : scripts) {
            const QJsonObject object = value.toObject();
            AppController::ScriptEntry script;
            script.id = object.value(QStringLiteral("id")).toString();
            script.name = object.value(QStringLiteral("name")).toString();
            script.fileName = object.value(QStringLiteral("fileName")).toString(scriptFileNameForId(script.id));
            script.updatedAt = object.value(QStringLiteral("updatedAt")).toString();
            if (script.id.isEmpty() || script.name.trimmed().isEmpty()) {
                continue;
            }
            script.code = readScriptFile(script.fileName);
            if (script.code.trimmed().isEmpty()) {
                script.code = defaultLuaScript();
            }
            result.scripts.append(script);
        }
    }

    return result;
}

bool saveScripts(QVector<AppController::ScriptEntry> &scripts, bool indexWritable)
{
    if (!indexWritable || !ensureScriptStorageDir()) {
        return false;
    }

    QJsonArray scriptRows;
    for (auto &script : scripts) {
        if (script.fileName.isEmpty()) {
            script.fileName = scriptFileNameForId(script.id);
        }
        if (!writeTextFile(scriptFilePath(script.fileName), script.code.toUtf8())) {
            return false;
        }

        QJsonObject object;
        object.insert(QStringLiteral("id"), script.id);
        object.insert(QStringLiteral("name"), script.name);
        object.insert(QStringLiteral("fileName"), script.fileName);
        object.insert(QStringLiteral("updatedAt"), script.updatedAt);
        scriptRows.append(object);
    }

    QJsonObject root;
    root.insert(QStringLiteral("version"), 1);
    root.insert(QStringLiteral("scripts"), scriptRows);
    return writeTextFile(scriptIndexPath(), QJsonDocument(root).toJson(QJsonDocument::Indented));
}

void removeScriptFile(const QString &fileName)
{
    if (!fileName.isEmpty()) {
        QFile::remove(scriptFilePath(fileName));
    }
}
}
